name: owl_workspace
description: "Owl Multi-Package Monorepo Workspace"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  melos: ^6.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
